#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : flask-restx
Version  : 0.2.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/5f/6e/f71db883f6228e09e7e8c7bf5f1068c0a853db992bcaebd105005b70c959/flask-restx-0.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/5f/6e/f71db883f6228e09e7e8c7bf5f1068c0a853db992bcaebd105005b70c959/flask-restx-0.2.0.tar.gz
Summary  : Fully featured framework for fast, easy and documented API development with Flask
Group    : Development/Tools
License  : BSD-3-Clause
Requires: flask-restx-python = %{version}-%{release}
Requires: flask-restx-python3 = %{version}-%{release}
Requires: Flask
Requires: Werkzeug
Requires: aniso8601
Requires: jsonschema
Requires: pytz
Requires: six
BuildRequires : Flask
BuildRequires : Werkzeug
BuildRequires : aniso8601
BuildRequires : buildreq-distutils3
BuildRequires : jsonschema
BuildRequires : pytz
BuildRequires : six

%description
===========
Flask RESTX
===========
.. image:: https://github.com/python-restx/flask-restx/workflows/Tests/badge.svg?tag=0.2.0&event=push
:target: https://github.com/python-restx/flask-restx/actions?query=workflow%3ATests
:alt: Tests status
.. image:: https://codecov.io/gh/python-restx/flask-restx/branch/master/graph/badge.svg
:target: https://codecov.io/gh/python-restx/flask-restx
:alt: Code coverage
.. image:: https://readthedocs.org/projects/flask-restx/badge/?version=0.2.0
:target: https://flask-restx.readthedocs.io/en/0.2.0/
:alt: Documentation status
.. image:: https://img.shields.io/pypi/l/flask-restx.svg
:target: https://pypi.org/project/flask-restx
:alt: License
.. image:: https://img.shields.io/pypi/pyversions/flask-restx.svg
:target: https://pypi.org/project/flask-restx
:alt: Supported Python versions
.. image:: https://badges.gitter.im/Join%20Chat.svg
:target: https://gitter.im/python-restx?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
:alt: Join the chat at https://gitter.im/python-restx
.. image:: https://img.shields.io/badge/code%20style-black-000000.svg
:target: https://github.com/psf/black
:alt: Code style: black

%package python
Summary: python components for the flask-restx package.
Group: Default
Requires: flask-restx-python3 = %{version}-%{release}

%description python
python components for the flask-restx package.


%package python3
Summary: python3 components for the flask-restx package.
Group: Default
Requires: python3-core
Provides: pypi(flask_restx)
Requires: pypi(werkzeug)
Requires: pypi(flask)
Requires: pypi(pytz)
Requires: pypi(six)
Requires: pypi(aniso8601)
Requires: pypi(jsonschema)

%description python3
python3 components for the flask-restx package.


%prep
%setup -q -n flask-restx-0.2.0
cd %{_builddir}/flask-restx-0.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1587561808
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
